wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688855898.726495
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 13
      - 23
      4: 3.9.17
      5: 0.15.5
      8:
      - 3
      - 5
