wandb_version: 1

model:
  desc: null
  value: MobileNetV3_small
epochs:
  desc: null
  value: 100
train_batch_size:
  desc: null
  value: 32
validation_batch_size:
  desc: null
  value: 32
optimizer:
  desc: null
  value: adam
learning_rate:
  desc: null
  value: 0.005
momentum:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688858814.946224
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.17
      5: 0.15.5
      8:
      - 3
      - 5
