project_name: MobileNetSmall
experiment_name: five_adam_20
dataset:
  annotation_path: C:\Users\User\projects\data\annotation\
  dataset_path: C:\Users\User\projects\data\
  targets:
  - call
  - dislike
  - like
  - ok
  - stop
  - no_gesture
  image_size:
  - 224
  - 224
  subset: -1
random_seed: 42
device: cuda
model:
  name: MobileNetV3_small
  pretrained: true
  freezed: false
  start_epoch: 0
  full_frame: false
optimizer:
  optimizer: adam
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0001
scheduler:
  start_factor: 0.001
train_params:
  epochs: 20
  num_workers: 16
  train_batch_size: 64
  validation_batch_size: 32
  early_stopping: 10
metric_params:
  metrics:
  - accuracy
  - f1_score
  - precision
  - recall
  average: weighted
