project_name: MobileNetSmall
experiment_name: sgd0_0005
dataset:
  annotation_path: C:\Users\User\projects\data\annotation\
  dataset_path: C:\Users\User\projects\data\
  targets:
    - call
    - dislike
    # - fist
    - like
    # - mute
    - ok
    - stop
    - no_gesture
  image_size: [224, 224]
  subset: -1
random_seed: 42
device: 'cuda'
model:
  name: 'MobileNetV3_small'  # 'MobileNetV3_large' or 'MobileNetV3_small' or 'ResNet18'
  pretrained: True
  freezed: False
  start_epoch: 0
  full_frame: False
optimizer:
  optimizer: sgd # adam, sgd, rmsprop
  lr: 0.005
  momentum: 0.9
  weight_decay: 0.0005
scheduler:
  start_factor: 0.001
train_params:
  epochs: 20
  num_workers: 16
  train_batch_size: 32
  validation_batch_size: 32
  early_stopping: 10
metric_params:
  metrics: ['accuracy', 'f1_score', 'precision', 'recall']
  average: 'weighted'
