experiment_name: MobileNetV3_small
project_name: HaGRID_Test
dataset:
  annotation_path: /media/weixiong0404/WINSON_EXT/data/annotation/
  dataset_path: /media/weixiong0404/WINSON_EXT/data/
  targets:
    - call
    - dislike
    - fist
    - like
    - mute
    - ok
    - stop
    - no_gesture
  image_size: [224, 224]
  subset: -1
random_seed: 42
device: 'cpu'
model:
  name: 'MobileNetV3_small'  # 'MobileNetV3_large' or 'MobileNetV3_small' or 'ResNet18'
  pretrained: True
  freezed: False
  start_epoch: 0
  full_frame: False
optimizer:
  optimizer: rmsprop # adam, sgd, rmsprop
  lr: 0.005
  momentum: 0.9
  weight_decay: 0.0005
scheduler:
  start_factor: 0.001
train_params:
  epochs: 100
  num_workers: 16
  train_batch_size: 32
  validation_batch_size: 32
metric_params:
  metrics: ['accuracy', 'f1_score', 'precision', 'recall']
  average: 'weighted'
