dataset:
  annotation_path: ../data/annotation/
  dataset_path: ../data/
  targets:
    - call
    - dislike
    - fist
    - like
    - mute
    - ok
    - stop
    - no_gesture
  image_size: [224, 224]
  subset: -1
random_seed: 42
device: 'cpu'
experiment_name: MobileNetV3_small
model:
  name: 'MobileNetV3_small'  # 'MobileNetV3_large' or 'MobileNetV3_small' or 'ResNet18'
  pretrained: False
  freezed: False
  start_epoch: 0
  checkpoint: /path/to/chackpoint
  full_frame: False
optimizer:
  lr: 0.005
  momentum: 0.9
  weight_decay: 0.0005
scheduler:
  start_factor: 0.001
train_params:
  epochs: 100
  num_workers: 16
  train_batch_size: 32
  test_batch_size: 64
  prefetch_factor: 16
metric_params:
  metrics: ['accuracy', 'f1_score', 'precision', 'recall']
  average: 'weighted'
